config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'photos' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'card'
      get 'exhibit'
      get 'trade'
      get 'sale'
      get 'news'
      get 'past'
      get 'task'
      get 'transaction'
      get 'deliver'
      get 'logout'
    end
    member do
      # get '/:product_id' => 'users#my_product', as: 'my_product'
      get 'my_product'
    end
    
  end
  resources :products, only: [:index, :show, :new, :edit, :destroy, :create,:update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'category/:category_id' => 'products#all_categories', as: "category" 
      delete '/:id/edit/:images_id' => "products#images_delete", as:"image_delete"
      post '/:id' => "products#update"
    end
  end
  resources :sellers, only: [:create, :show, :update] do
    member do
      post 'pay' ,to: 'sellers#pay' 
    end
  end

  resources :identifications
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'delete', to: 'card#delete'
    end
  end
  resources :photos
end

app/models/seller.rb
class Seller < ApplicationRecord

  
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only:[:show, :pay, :update]

  require 'payjp'

  def show
    @user = User.find(@product.user_id)
    card = Card.where(user_id: current_user.id).first
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
  if card.blank? || current_user.id == @product.user_id
    #登録された情報がない場合にトップ画面に移動
    redirect_to root_path
  else
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    #保管した顧客IDでpayjpから情報取得
    customer = Payjp::Customer.retrieve(card.customer_id)
    #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
    @default_card_information = customer.cards.retrieve(card.card_id)
  end

  end

  def update
    @product.update(status: '2')

    redirect_to root_path #トップ画面に移動（完了画面を作ればそちらの方がベター）
  end

  def new
  end
  

  def index
  end

  def pay
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_PRIVATE_KEY]
    Payjp::Charge.create(
    amount: @product.price, #支払金額を入力
    customer: card.customer_id, #顧客ID
    currency: 'jpy', #日本円
    )
  update
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end


end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/show.html.haml
.product-contents
  %header.product-header
    %h1
      = link_to('#', {}) do
        = image_tag "mercari_logo_horizontal.png", :class => "header-image"
.buy-comfirm
  .buy-comfirm__header
    %h2 購入内容の確認
  .buy-comfirm__buy
    .buy-comfirm__buy__inner
      .buy-comfirm__buy__inner__item
        .buy-comfirm__buy__inner__item__photo
          = image_tag(@product.images[0].variant(resize: "64x120"))
        .buy-comfirm__buy__inner__item__name
          %p 
            = @product.name
      .buy-comfirm__buy__inner__subtotal-price
        = @product.price.to_s(:delimited)
        .buy-comfirm__buy__inner__subtotal-price__shipping-fee
          %p 
            = @product.burden.name
      .buy-comfirm__buy__inner__total-price
        .buy-comfirm__buy__inner__total-price__cell
          支払い金額
        .buy-comfirm__buy__inner__total-price__cell
          ¥
          = @product.price.to_s(:delimited)
      = link_to pay_seller_path(@product.id), method: :post do
        %button.buy-comfirm__buy__inner__buy-btn
          購入する
  .buy-comfirm__delivery
    .buy-comfirm__delivery__inner
      %h3 配送先
      .buy-comfirm__delivery__inner__address
        〒
        =@user.postal_code
        %br 
          = @user.prefecture.name
          = @user.city
          = @user.address
      .buy-comfirm__delivery__inner__edit-btn
        = link_to "変更する　>", "seller_path", method: :get  
  .buy-comfirm__pay-method
    .buy-comfirm__pay-method__inner
      %h3 支払い方法
      .buy-comfirm__pay-method__inner__info
        - if @default_card_information.blank?
          %br /
        - else
          -#以下カード情報を表示
          = "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
      .buy-comfirm__pay-method__inner__edit-btn
        = link_to "変更する　>", "seller_path", method: :get  
.product-contents
  %footer.product-footer
    %nav
      %ul.clearfix
        %li
          = link_to('#', {}) do
            プライバシーポリシー
        %li
          = link_to('#', {}) do
            メルカリ利用規約
        %li
          = link_to('#', {}) do
            特定商取引に関する表記
    = link_to('#', class:'bottom-image') do
      = image_tag(src= "logo-gray.svg")
    %p
      %small© 2019 Mercari

      

  