config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'photos' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'card'
      get 'exhibit'
      get 'trade'
      get 'sale'
      get 'news'
      get 'past'
      get 'task'
      get 'transaction'
      get 'deliver'
      get 'logout'
    end
    member do
      # get '/:product_id' => 'users#my_product', as: 'my_product'
      get 'my_product'
    end
    
  end
  resources :products, only: [:index, :show, :new, :edit, :destroy, :create,:update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'category/:category_id' => 'products#all_categories', as: "category" 
      delete '/:id/edit/:images_id' => "products#images_delete", as:"image_delete"
      post '/:id' => "products#update"
    end
  end
  resources :sellers, only: [:create, :show, :update] do
    member do
      post 'pay' ,to: 'sellers#pay' 
    end
  end

  resources :identifications
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'delete', to: 'card#delete'
    end
  end
  resources :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :products
  # has_many :goods
  # has_many :contacts
  # belongs_to :credit
  # has_many :evaluation
  has_one :idntification
  # belongs_to :buyer
  has_many :cards
  has_many :sns_credentials, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.where(uid: request.env["omniauth.auth"].uid)
    if @user.present?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "facebook"
      sign_in_and_redirect @user[0] 
    else
      session["devise.facebook_data"] = request.env['omniauth.auth']
      @user = User.new()
      @sns_credential = SnsCredential.new()
      if data = session["devise.facebook_data"]["extra"]["raw_info"]
        @user.nickname = data["name"] if @user.nickname.blank?
        @user.email = data["email"] if @user.email.blank?
        @user.provider = "facebook" if @user.provider.blank?
        @user.uid = data["id"] if @user.uid.blank?
        @user.password = Devise.friendly_token[0,20] if @user.password.blank?
        render 'devise/registrations/new'
      end
    end
  end


  def google_oauth2
    @user = User.where(uid: request.env["omniauth.auth"].uid)
    if @user.present?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user[0] 
    else
      session["devise.google_data"] = request.env['omniauth.auth']
      @user = User.new()
      @sns_credential = SnsCredential.new()
      if data = session["devise.google_data"]["extra"]["raw_info"]
        @user.nickname = data["name"] if @user.nickname.blank?
        @user.email = data["email"] if @user.email.blank?
        @user.provider = "google" if @user.provider.blank?
        @user.uid = data["sub"] if @user.uid.blank?
        @user.password = Devise.friendly_token[0,20] if @user.password.blank?
        render 'devise/registrations/new'
      end
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :new

  def index
  end

  def show
  end

  def create
  end

  def new
  end

  def edit
  end
  
  def logout
  end

  def card
  end

  def exhibit
    @my_products = Product.includes(:user).where(user_id: current_user.id).where(status:'1')
  end

  def my_product
    @product = Product.find(params[:id])
    @user = User.find(@product.user_id )
    @images = @product.images
  end

  def trade
    @my_products = Product.includes(:user).where(user_id: current_user.id).where(status:'3')
  end

  def sale
    @my_products = Product.includes(:user).where(user_id: current_user.id).where(status:'2')
  end

  def news
  end

  def past
  end

  def task
  end

  def transaction
  end

  def deliver
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    if params.require(:user)[:last_name]
      params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :prefecture_id, :city, :address, :building, :phone_number, :postal_code)
    else
      params.require(:user).permit(:nickname, :comment)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['products', 'show']
  - breadcrumb :show

  = breadcrumbs separator: " &rsaquo; "

app/views/users/_signup_footer.html.haml
.user-info__footer
  %nav
    %ul.clearfix
      %li
        = link_to('#', {}) do
          プライバシーポリシー
      %li
        = link_to('#', {}) do
          メルカリ利用規約
      %li
        = link_to('#', {}) do
          特定商取引に関する表記
  = link_to('#', class:'bottom-image') do
    = image_tag(src= "logo-gray.svg")
  %p
    %small© 2019 Mercari

app/views/users/_signup_header.html.haml
.user-info__header
  .user-info__header__mercari-icon
    = link_to(root_path, {}) do
      = image_tag "mercari_logo_horizontal.png", class: "user-info__header__mercari-icon__image"
  .user-info__header__progress
    .user-info__header__progress__flat-bar
      .user-info__header__progress__flat-bar__left
      .user-info__header__progress__flat-bar__right
    .user-info__header__progress__current-now
      会員情報
      .user-info__header__progress__current-now__round
    .user-info__header__progress__current
      電話番号認証
      .user-info__header__progress__current__round
    .user-info__header__progress__current
      お届け先住所入力
      .user-info__header__progress__current__round
    .user-info__header__progress__current
      支払い方法
      .user-info__header__progress__current__round
    .user-info__header__progress__current
      完了
      .user-info__header__progress__current__round

app/views/users/card.html.haml
.main-box
  .main-box__header
    = render 'products/header'
  .main
    .main__user
      .input-bar
        .input-bar__title
          支払い方法
        .input-bar__card-main
          .input-bar__card-main__title
            クレジットカード
          .input-bar__card-main__box
            .input-bar__card-main__box__btm
              = link_to '#',class: 'credit-card-btm' do
                = fa_icon 'credit-card'
                クレジットカードを追加する
          .input-bar__card-main__textbtm 
            = link_to '支払い方法について','#',class: 'input-bar__card-main__textbtm__link'
            = fa_icon 'angle-right document__btm'
    .main__user-bar
      .side-nav
        %ul.user-list
          %li.user-list__box
            = link_to '/users',class: 'user-list__box__btm' do
              マイページ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/news',class: 'user-list__box__btm' do
              お知らせ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/task',class: 'user-list__box__btm' do
              やることリスト
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/products/new',class: 'user-list__box__btm' do
              出品する
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/exhibit',class: 'user-list__box__btm' do
              出品した商品-出品中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/sale',class: 'user-list__box__btm' do
              出品した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/trade',class: 'user-list__box__btm' do
              出品した商品-売却済み
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/transaction',class: 'user-list__box__btm' do
              購入した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/past',class: 'user-list__box__btm' do
              購入した商品-過去の取引
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ニュース一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              評価一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ガイド
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              お問い合わせ
              = fa_icon 'angle-right side-bar'
        .com
          メルペイ
        %ul.user-list
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              売上・振込申請
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ポイント
              = fa_icon 'angle-right side-bar'
        .com
          設定
        %ul.user-list
          %li.user-list__box
            = link_to edit_user_path(current_user),class: 'user-list__box__btm' do
              プロフィール
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/deliver',class: 'user-list__box__btm' do
              発送元・お届け先住所変更
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/card',class: 'user-list__box__btm choice' do
              支払い方法
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              メール/パスワード
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to edit_identification_path(current_user),class: 'user-list__box__btm' do
              本人情報
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              電話番号の確認
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/logout',class: 'user-list__box__btm' do
              ログアウト
              = fa_icon 'angle-right side-bar'
= render 'users/footer'
= render 'products/bigicon'

app/views/users/exhibit.html.haml
.main-box
  .main-box__header
    = render 'products/header'
  .main
    .main__user
      .user-sale-products
        .user-sale-products__header
          出品した商品
        .info-tab
          = link_to '出品中','/users/exhibit',class: 'info-tab__btm active' 
          = link_to '取引中','/users/sale',class: 'info-tab__btm' 
          = link_to '売却済み','/users/trade',class: 'info-tab__btm' 
        .info-content
          .info-content__details
            - if @my_products[0]
              - @my_products.each do |my_product|
                - if my_product.images[0]
                  = link_to my_product_user_path(my_product.id) do
                    .info-content__details__my-item-list
                      .info-content__details__my-item-list__image
                        = image_tag(my_product.images[0].variant(resize: "48x48"))
                      .info-content__details__my-item-list__content
                        .info-content__details__my-item-list__content__name
                          = my_product.name
                        .info-tcontent__details__my-item-list_content__detail
                          .info-content__details__my-item-list__content__detail--like
                            ♡
                          .info-content__details__my-item-list__content__detail--comment
                            💬
                          .info-content__details__my-item-list__content__detail--status 
                            出品中                   
                      .info-content__details__my-item-list__right-arrow
            - else
              .info-content__details__none
                出品中の商品がありません
    .main__user-bar
      .side-nav
        %ul.user-list
          %li.user-list__box
            = link_to '/users',class: 'user-list__box__btm' do
              マイページ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/news',class: 'user-list__box__btm' do
              お知らせ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/task',class: 'user-list__box__btm' do
              やることリスト
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/products/new',class: 'user-list__box__btm' do
              出品する
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/exhibit',class: 'user-list__box__btm choice' do
              出品した商品-出品中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/sale',class: 'user-list__box__btm' do
              出品した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/trade',class: 'user-list__box__btm' do
              出品した商品-売却済み
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/transaction',class: 'user-list__box__btm' do
              購入した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/past',class: 'user-list__box__btm' do
              購入した商品-過去の取引
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ニュース一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              評価一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ガイド
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              お問い合わせ
              = fa_icon 'angle-right side-bar'
        .com
          メルペイ
        %ul.user-list
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              売上・振込申請
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ポイント
              = fa_icon 'angle-right side-bar'
        .com
          設定
        %ul.user-list
          %li.user-list__box
            = link_to edit_user_path(current_user),class: 'user-list__box__btm' do
              プロフィール
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/deliver',class: 'user-list__box__btm' do
              発送元・お届け先住所変更
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/card',class: 'user-list__box__btm' do
              支払い方法
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              メール/パスワード
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to edit_identification_path(current_user),class: 'user-list__box__btm' do
              本人情報
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              電話番号の確認
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/logout',class: 'user-list__box__btm' do
              ログアウト
              = fa_icon 'angle-right side-bar'
= render 'users/footer'
= render 'products/bigicon'

app/views/users/my_product.html.haml
.header
  = render 'products/header'

.product
  .product__details
    .product__details-name
      = @product.name
    .product__details-main-content.clearfix
      .product__details-photo
        .product__details-photo__all
          - @images.each_with_index do |image,i|
            .product__details-photo__all__selected{"data-big-photo-id": "#{i}"}
              = image_tag(image.variant(resize: "300x300"))
        .product__details-photo__all-img-box
          - @images.each_with_index do |image,i|
            .product__details-photo__all-img-box__dot{"data-small-photo-id": "#{i}"}
              = image_tag(image.variant(resize: "60x60"), id: "small_photo")



      %table.product__details-table
        %tr
          %th 出品者
          %td
            = link_to  "product_path", method: :get  do 
              = @user.nickname
        %tr
          %th カテゴリー
          %td
            = link_to category_products_path(category_id: @product.category_id ), method: :get do
              = @product.category_id
        %tr
          %th ブランド
          %td
            = link_to  "product_path", method: :get  do
              = @product.brand
        %tr
          %th 商品のサイズ
          %td 
            = @product.size.name
        %tr
          %th 商品の状態
          %td 
            = @product.state.name
        %tr
          %th 送料の負担
          %td 
            = @product.burden.name
        %tr
          %th 配送の方法
          %td
            = @product.shipping.name
        %tr
          %th 配送元地域
          %td
            = link_to  "product_path", method: :get  do
              = @product.region.name
        %tr
          %th 発送日の目安
          %td
            = @product.leadtime.name

    .product__details-price-box
      .product__details-price
        = @product.price.to_s(:delimited)
      .product__details-price-tax
        (税込)
      .product__details-price-shipping-fee
        = @product.burden.name
    .product__details-buy-btn
      - unless user_signed_in? && current_user.id == @product.user_id 
        %button.buy-btn 購入する
    .product__details-description
      .product__details-description-inner
        = @product.explain

  .product__change-box
    .product__change-box--edit
      = link_to edit_product_path(id: @product.id) ,method: :get do
        商品の編集
    .product__change-box--or
      or
    .product__change-box--stop
      出品を一旦停止する
    .product__change-box--delete#delete-btn
      この商品を削除する

  .product__messages
    .product__messages-notice
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .product__messages-textarea
      %textarea.message-textarea
      %button.message-btn コメントする

= render 'users/footer'



-# 削除モーダル
.delete-modal
  .delete-modal__box
    .delete-modal__box--content
      確認
      %br
      削除すると二度と復活出来ません。
      %br
      削除する代わりに停止することもできます。
      %br
      %br
      本当に削除しますか？
  .delete-modal__select.clearfix
    .delete-modal__select--cancel
      キャンセル
    .delete-modal__select--delete
      = link_to product_path(id: @product.id), method: :delete do
        削除

app/views/users/new.html.haml
-# １ページ目
.product-contents
  %header.product-header
    %h1
      = link_to('#', {}) do
        = image_tag "mercari_logo_horizontal.png", :class => "header-image"
.sign-up__content
  .sign-up__content__header
    %h2 新規会員登録
  .sign-up__content__registation
    .sign-up__content__registation__box
      %button.sign-up__content__registation__box__mail
        %i.fa.fa-envelope-o
          =link_to "メールアドレスで登録する", "/users/sign_up" 
      %button.sign-up__content__registation__box__facebook
        %i.fa.fa-facebook-official
          =link_to "Facebookで登録する",user_facebook_omniauth_authorize_path,method: :post
      %button.sign-up__content__registation__box__google
        %i.fa.fa-google

          =link_to "Googleで登録する",user_google_oauth2_omniauth_authorize_path,method: :post
  .sign-up__content__graybox
.product-contents
  %footer.product-footer
    %nav
      %ul.clearfix
        %li
          = link_to('#', {}) do
            プライバシーポリシー
        %li
          = link_to('#', {}) do
            メルカリ利用規約
        %li
          = link_to('#', {}) do
            特定商取引に関する表記
    = link_to('#', class:'bottom-image') do
      = image_tag(src= "logo-gray.svg")
    %p
      %small© 2019 Mercari

app/views/users/trade.html.haml
.main-box
  .main-box__header
    = render 'products/header'
  .main
    .main__user
      .user-sale-products
        .user-sale-products__header
          出品した商品
        .info-tab
          = link_to '出品中','/users/exhibit',class: 'info-tab__btm'
          = link_to '取引中','/users/sale',class: 'info-tab__btm'
          = link_to '売却済み','/users/trade',class: 'info-tab__btm active'
        .info-content
          .info-content__details
            - if @my_products[0]
              - @my_products.each do |my_product|
                - if my_product.images[0]
                  = link_to my_product_user_path(my_product.id) do
                    .info-content__details__my-item-list
                      .info-content__details__my-item-list__image
                        = image_tag(my_product.images[0].variant(resize: "48x48"))
                      .info-content__details__my-item-list__content
                        .info-content__details__my-item-list__content__name
                          = my_product.name
                        .info-tcontent__details__my-item-list_content__detail
                          .info-content__details__my-item-list__content__detail--like
                            ♡
                          .info-content__details__my-item-list__content__detail--comment
                            💬
                          .info-content__details__my-item-list__content__detail--status 
                            出品中
                      .info-content__details__my-item-list__right-arrow
            - else
              .info-content__details__none
                売却済みの商品がありません
    .main__user-bar
      .side-nav
        %ul.user-list
          %li.user-list__box
            = link_to '/users',class: 'user-list__box__btm' do
              マイページ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/news',class: 'user-list__box__btm' do
              お知らせ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/task',class: 'user-list__box__btm' do
              やることリスト
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/products/new',class: 'user-list__box__btm' do
              出品する
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/exhibit',class: 'user-list__box__btm' do
              出品した商品-出品中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/sale',class: 'user-list__box__btm' do
              出品した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/trade',class: 'user-list__box__btm choice' do
              出品した商品-売却済み
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/transaction',class: 'user-list__box__btm' do
              購入した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/past',class: 'user-list__box__btm' do
              購入した商品-過去の取引
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ニュース一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              評価一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ガイド
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              お問い合わせ
              = fa_icon 'angle-right side-bar'
        .com
          メルペイ
        %ul.user-list
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              売上・振込申請
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ポイント
              = fa_icon 'angle-right side-bar'
        .com
          設定
        %ul.user-list
          %li.user-list__box
            = link_to edit_user_path(current_user),class: 'user-list__box__btm' do
              プロフィール
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/deliver',class: 'user-list__box__btm' do
              発送元・お届け先住所変更
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/card',class: 'user-list__box__btm' do
              支払い方法
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              メール/パスワード
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to edit_identification_path(current_user),class: 'user-list__box__btm' do
              本人情報
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              電話番号の確認
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/logout',class: 'user-list__box__btm' do
              ログアウト
              = fa_icon 'angle-right side-bar'
= render 'users/footer'
= render 'products/bigicon'