config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'photos' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'card'
      get 'exhibit'
      get 'trade'
      get 'sale'
      get 'news'
      get 'past'
      get 'task'
      get 'transaction'
      get 'deliver'
      get 'logout'
    end
    member do
      # get '/:product_id' => 'users#my_product', as: 'my_product'
      get 'my_product'
    end
    
  end
  resources :products, only: [:index, :show, :new, :edit, :destroy, :create,:update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'category/:category_id' => 'products#all_categories', as: "category" 
      delete '/:id/edit/:images_id' => "products#images_delete", as:"image_delete"
      post '/:id' => "products#update"
    end
  end
  resources :sellers, only: [:create, :show, :update] do
    member do
      post 'pay' ,to: 'sellers#pay' 
    end
  end

  resources :identifications
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'delete', to: 'card#delete'
    end
  end
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burden.rb
class Burden < ActiveHash::Base
  self.data = [
    {id: 0, name: '----'},
    {id: 1, name: '送料込み（出品者負担）'},
    {id: 2, name: '着払い（購入者負担）'},
  ]
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_ancestry
end

app/models/identification.rb
class Identification < ApplicationRecord
end

app/models/leadtime.rb
class Leadtime < ActiveHash::Base
  self.data = [
    {id: 0, name: '----'},
    {id: 1, name: '１日〜２日で発送'},
    {id: 2, name: '２日〜３日で発送'},
    {id: 3, name: '４日〜７日で発送'},
  ]
end

app/models/photo.rb
class Photo < ApplicationRecord
  # has_many_attached :images
  # belongs_to :product, optional: true
  
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 0, name: '----'},
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :goods
  has_many :contacts
  has_many_attached :images
  # has_many :photos
  belongs_to :category
  # accepts_nested_attributes_for :photos

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region
  belongs_to_active_hash :burden
  belongs_to_active_hash :state
  belongs_to_active_hash :leadtime
  belongs_to_active_hash :shipping
  belongs_to_active_hash :size


  # 前へ、次へボタンの実装
  def previous
    user.products.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.products.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end


end

app/models/region.rb
class Region < ActiveHash::Base
  self.data = [
      {id: 0, name: '----'},
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/seller.rb
class Seller < ApplicationRecord

  
end

app/models/shipping.rb
class Shipping < ActiveHash::Base
  self.data = [
    {id: 0, name: '----'},
    {id: 1, name: '未定'},
    {id: 2, name: 'らくらくメルカリ便'},
    {id: 3, name: 'ゆうメール'},
    {id: 4, name: 'レターパック'},
    {id: 5, name: '普通郵便（定形、定形外）'},
    {id: 6, name: 'クロネコヤマト'},
    {id: 7, name: 'ゆうパック'},
    {id: 8, name: 'クリックポスト'},
    {id: 9, name: 'ゆうパケット'},
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 0, name: '----'},
    {id: 1, name: 'XXS以下'},
    {id: 2, name: 'XS(SS)'},
    {id: 3, name: 'S'},
    {id: 4, name: 'M'},
    {id: 5, name: 'L'},
    {id: 6, name: 'XL(LL)'},
    {id: 7, name: '2XL(3L)'},
    {id: 8, name: '3XL(4L)'},
    {id: 9, name: '4XL(5L)以上'},
    {id: 10, name: 'FREE SIZE'},
  ]
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/state.rb
class State < ActiveHash::Base
  self.data = [
    {id: 0, name: '----'},
    {id: 1, name: '新品・未使用'},
    {id: 2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'},
    {id: 4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'},
    {id: 6, name: '全体的に状態が悪い'},
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :products
  # has_many :goods
  # has_many :contacts
  # belongs_to :credit
  # has_many :evaluation
  has_one :idntification
  # belongs_to :buyer
  has_many :cards
  has_many :sns_credentials, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture


end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  end

  def create
  end

  def edit
    @identification = Identification.find_by(user_id: current_user.id)
  end

  def update
    @identification = Identification.find_by(user_id: current_user.id)
    if @identification.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def show
  end

  private

  def user_params
    params.require(:identification).permit(:postal_code, :prefecture, :city, :address, :building)
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/identifications/edit.html.haml
.main-box
  .main-box__header
    = render 'products/header'
  .main
    .main__user
      .input-bar
        .input-bar__title
          本人情報の登録
        .input-bar__form-field
          = form_with model: @identification, url: identification_path(@identification), local: true,metod: :patch do |f|
            .input-bar__form-field__document
              %p 
                お客さまの本人情報をご登録ください。
                %br
                登録されたお名前生年月日を変更する場合、本人確認書類の提出が必要になります。
              %p.input-bar__form-field__document__btm
                = link_to '本人確認書類のアップロードについて','#'
                = fa_icon 'angle-right document__btm'
            .input-bar__form-field__box
              %label
                お名前
              %p
                = @identification.last_name
                = @identification.first_name
            .input-bar__form-field__box
              %label
                お名前カナ
              %p
                = @identification.last_name_kana
                = @identification.first_name_kana
            .input-bar__form-field__box
              %label
                生年月日
              %p
                = @identification.birthday
            .input-bar__form-field__box
              %label
                郵便番号
              %span
                任意
                %br
              = f.text_field :postal_code, class: 'form-input-box', placeholder: '例）1234567'
            .input-bar__form-field__box
              %label
                都道府県
              %span
                任意
                %br
              .form-select-box
                = fa_icon 'angle-down select-btm-box'
                = f.select :prefecture, ["--","北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県"],{}, class: "form-select-box__selecter"
            .input-bar__form-field__box
              %label
                市区町村
              %span
                任意
                %br
              = f.text_field :city, class: 'form-input-box', placeholder: '例）横浜市緑区'
            .input-bar__form-field__box
              %label
                番地
              %span
                任意
                %br
              = f.text_field :address, class: 'form-input-box', placeholder: '例）青山1-1-1'
            .input-bar__form-field__box
              %label
                建物名
              %span
                任意
                %br
              = f.text_field :building, class: 'form-input-box', placeholder: '例）柳ビル103'
            = f.submit '登録する', class: 'identification-registration-btn'
            .input-bar__form-field__box
              %p.input-bar__form-field__box__btm
                = link_to '本人情報の登録について','#'
                = fa_icon 'angle-right document__btm'
    .main__user-bar
      .side-nav
        %ul.user-list
          %li.user-list__box
            = link_to '/users',class: 'user-list__box__btm' do
              マイページ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/news',class: 'user-list__box__btm' do
              お知らせ
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/task',class: 'user-list__box__btm' do
              やることリスト
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              出品する
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/exhibit',class: 'user-list__box__btm' do
              出品した商品-出品中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/sale',class: 'user-list__box__btm' do
              出品した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/trade',class: 'user-list__box__btm' do
              出品した商品-売却済み
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/transaction',class: 'user-list__box__btm' do
              購入した商品-取引中
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/past',class: 'user-list__box__btm' do
              購入した商品-過去の取引
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ニュース一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              評価一覧
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ガイド
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              お問い合わせ
              = fa_icon 'angle-right side-bar'
        .com
          メルペイ
        %ul.user-list
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              売上・振込申請
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              ポイント
              = fa_icon 'angle-right side-bar'
        .com
          設定
        %ul.user-list
          %li.user-list__box
            = link_to edit_user_path(current_user),class: 'user-list__box__btm' do
              プロフィール
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/deliver',class: 'user-list__box__btm' do
              発送元・お届け先住所変更
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/card',class: 'user-list__box__btm' do
              支払い方法
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              メール/パスワード
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/identifications/new',class: 'user-list__box__btm choice' do
              本人情報
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '#',class: 'user-list__box__btm' do
              電話番号の確認
              = fa_icon 'angle-right side-bar'
          %li.user-list__box
            = link_to '/users/logout',class: 'user-list__box__btm' do
              ログアウト
              = fa_icon 'angle-right side-bar'
= render 'users/footer'
= render 'products/bigicon'