config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',registrations: 'photos' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    collection do
      get 'card'
      get 'exhibit'
      get 'trade'
      get 'sale'
      get 'news'
      get 'past'
      get 'task'
      get 'transaction'
      get 'deliver'
      get 'logout'
    end
    member do
      # get '/:product_id' => 'users#my_product', as: 'my_product'
      get 'my_product'
    end
    
  end
  resources :products, only: [:index, :show, :new, :edit, :destroy, :create,:update] do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'category/:category_id' => 'products#all_categories', as: "category" 
      delete '/:id/edit/:images_id' => "products#images_delete", as:"image_delete"
      post '/:id' => "products#update"
    end
  end
  resources :sellers, only: [:create, :show, :update] do
    member do
      post 'pay' ,to: 'sellers#pay' 
    end
  end

  resources :identifications
  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'delete', to: 'card#delete'
    end
  end
  resources :photos
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :goods
  has_many :contacts
  has_many_attached :images
  # has_many :photos
  belongs_to :category
  # accepts_nested_attributes_for :photos

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region
  belongs_to_active_hash :burden
  belongs_to_active_hash :state
  belongs_to_active_hash :leadtime
  belongs_to_active_hash :shipping
  belongs_to_active_hash :size


  # 前へ、次へボタンの実装
  def previous
    user.products.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.products.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :all_categories]
  before_action :set_product, only:[:show, :destroy, :update, :edit]
  before_action :set_user, only:[:show]
  
  def index
    @parents = Category.where(ancestry:  nil)
    @products = Product.all

    @ladys_products = Product.where("category_id <= ?", 199).where(status:'1').order('created_at DESC').limit(4)
    @mens_products = Product.where("category_id >= ?", 200).where("category_id <= ?", 345).where(status:'1').order('created_at DESC').limit(4)
    @babys_products = Product.where("category_id >= ?", 346).where("category_id <= ?", 480).where(status:'1').order('created_at DESC').limit(4)
    @beauties_products = Product.where("category_id >= ?", 798).where("category_id <= ?", 897).where(status:'1').order('created_at DESC').limit(4)

    @chanel = Product.where(brand: "シャネル").where(status:'1').order('created_at DESC').limit(4)
    @vuitton = Product.where(brand: "ルイ ヴィトン").where(status:'1').order('created_at DESC').limit(4)
    @nike = Product.where(brand: "ナイキ").where(status:'1').order('created_at DESC').limit(4)
    @supreme = Product.where(brand: "シュプリーム").where(status:'1').order('created_at DESC').limit(4)
  end

  def show
    @my_products = Product.where(user_id: @product.user_id).where.not(id: params[:id]).order('created_at DESC').limit(6)
    @brand = Product.where(brand: @product.brand).where.not(id: params[:id]).order('created_at DESC').limit(6)
    @images = @product.images
    @category = Category.find(@product.category_id)
    @category2 = Category.find(@product.child_category_id)
    @category3 = Category.find(@product.grandchild_category_id)
  end

  def all_categories
    id = params[:category_id]
    id = id.to_i
    if id >= 1 && id <= 199
      category_id_devided(1,199,"レディース")
    elsif id >= 200 && id <= 345
      category_id_devided(200,345,"メンズ")
    elsif id >= 346 && id <= 480
      category_id_devided(346,480,"ベビー・キッズ")
    elsif id >= 481 && id <= 624
      category_id_devided(481,624,"インテリア・住まい・小物")
    elsif id >= 625 && id <= 684
      category_id_devided(625,684,"本・音楽・ゲーム")
    elsif id >= 685 && id <= 797
      category_id_devided(685,797,"おもちゃ・ホビー・グッズ")
    elsif id >= 798 && id <= 897
      category_id_devided(798,897,"コスメ・香水・美容")
    elsif id >= 898 && id <= 983
      category_id_devided(898,983,"家電・スマホ・カメラ")
    elsif id >= 984 && id <= 1092
      category_id_devided(984,1092,"スポーツ・レジャー")
    elsif id >= 1093 && id <= 1146
      category_id_devided(1093,1146,"ハンドメイド")
    elsif id >= 1147 && id <= 1206
      category_id_devided(1147,1206,"チケット")
    elsif id >= 1207 && id <= 1269
      category_id_devided(1207,1269,"自動車・オートバイ")
    elsif id >= 1270 && id <= 1338
      category_id_devided(1270,1338,"その他")
    else
      redirect_to :root
    end
  end

  def category_id_devided (a,b,c)
    @category_products = Product.where("category_id >= ?", a).where("category_id <= ?", b).where(status:'1').order('created_at DESC')
    @category_name = c
  end

  def new
    @product = Product.new
    @parent_category_array =  ["---"]
    Category.where(ancestry:  nil).each do |parent|
    @parent_category_array << [parent.name,parent.id]
    end
  end

  def destroy
    if current_user.id == @product.user_id
      if @product.destroy
      redirect_to :root
      else
        render :destroy
      end
    else
      redirect_to :root
    end
  end

  def images_delete
    @image_delete = Product.find(params[:id]).images.find(params[:images_id])
    if @image_delete.purge
      redirect_to :edit_product
    end
  end

  def edit
    @product = Product.find(params[:id])
    if current_user.id == @product.user_id
      @images = @product.images
      parent_category_id = Category.find(@product.category_id)
      child_category_id = Category.find(@product.child_category_id)
      grandchild_category_id = Category.find(@product.grandchild_category_id)
      
      @parent_category_array =  ["---"]
      Category.where(ancestry: nil).each do |parent|
      @parent_category_array << [parent.name,parent.id]
      end
      @child_category_array =  ["---"]
      Category.where(ancestry: "#{parent_category_id.id}").each do |parent|
      @child_category_array << [parent.name,parent.id]
      end
      @grandchild_category_array =  ["---"]
      Category.where(ancestry: "#{parent_category_id.id}" + "/" + "#{child_category_id.id}").each do |parent|
      @grandchild_category_array << [parent.name,parent.id]
      end
    else
      redirect_to :root
    end
  end

  def update
    if @product.update(create_params)
      if params[:product][:image_ids] && params[:product][:images]
          @product.images.attach(params[:product][:images])
          params[:product][:image_ids].each do |image_id|
          image = @product.images.find(image_id)
          image.purge
        end
      elsif params[:product][:images]
        @product.images.attach(params[:product][:images])
      elsif params[:product][:image_ids] 
        params[:product][:image_ids].each do |image_id|
        image = @product.images.find(image_id)
        image.purge
        end
      end
    # redirect_to :root
    else
      render :edit
    end
  end

  def get_category_children
    @category_children = Category.find_by(id: params[:id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find_by(id: params[:child_id]).children
  end

  def create
    @production = Product.create(create_params)
    @production.images.attach(params[:product][:images])
  end

  private
  def create_params
    params.require(:product).permit(:name, :price, :category_id,:child_category_id, :grandchild_category_id, :brand, :size_id, :state_id, :burden_id, :shipping_id, :region_id, :leadtime_id, :explain).merge(user_id: current_user.id, status: "1" )
  end

  def set_product
    if params[:id] == "0"
      redirect_to :root
    else
      @product = Product.find(params[:id])
    end
  end

  def set_user
    @user = User.find(@product.user_id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_bigicon.html.haml
= link_to('/products/new', class: 'fotter-exhibition-btn') do
  .fotter-exhibition-btn__name
    出品
  %i.fa.fa-camera

app/views/products/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['users', 'index']
  - breadcrumb :users

- when ['users', 'card']
  - breadcrumb :card

- when ['users', 'edit']
  - breadcrumb :edit

- when ['users', 'exhibit']
  - breadcrumb :exhibit

- when ['users', 'trade']
  - breadcrumb :trade

- when ['users', 'news']
  - breadcrumb :news

- when ['users', 'task']
  - breadcrumb :task

- when ['users', 'past']
  - breadcrumb :past

- when ['users', 'transaction']
  - breadcrumb :transaction

- when ['users', 'sale']
  - breadcrumb :sale

- when ['identifications', 'edit']
  - breadcrumb :identification

- when ['users', 'logout']
  - breadcrumb :logout

- when ['users', 'deliver']
  - breadcrumb :deliver

= breadcrumbs separator: " &rsaquo; "

app/views/products/_header.html.haml
.header
  .header__inner
    .header__inner__top
      .header__inner__top__left
        %h1
          =link_to '/' do
            =image_tag "mercari_logo_horizontal.png",alt:"メルカリ"
      %form.header__inner__top__form
        %input{type:"search",name:"keyword",placeholder:"何かお探しですか？"}
        %i.header__inner__top__form__icon
    .header__inner__list
      %nav.header__inner__list__left
        %ul.header__inner__list__left__box
          %li.header__inner__list__left__box__parent
            = link_to "カテゴリーから探す"
            %i.header__inner__list__left__box__parent__icon
            %ul.header-category
            - Category.where(ancestry: nil).each do |parent|
              .header-category-list
                = link_to parent.name, category_products_path(parent.id),class:"header-category-list-link"
                %ul.header-category-child
                  - parent.children.each do |child|
                    .header-category-childlist
                      = child.name
                      %ul.header-category-grand
                        - child.children.each do |grandchild|
                          .header-category-grandlist
                            =grandchild.name
                    
          %li.header__inner__list__left__box__cousin
            = link_to "ブランドから探す"
            %i.header__inner__list__left__box__cousin__icon
      .header__inner__list__right
        -if user_signed_in?
          %ui.header__inner__list__right__box
            .header__inner__list__right__box__like
              %i.header__inner__list__right__box__like__icon
                =link_to "いいね！一覧"
            .header__inner__list__right__box__notice
              %i.header__inner__list__right__box__notice__icon
                =link_to "お知らせ",news_users_path
            .header__inner__list__right__box__do
              %i.header__inner__list__right__box__do__icon
                =link_to "やることリスト",task_users_path
            .header__inner__list__right__box__my
              .header__inner__list__right__box__my__text
                =link_to "マイページ",users_path
              .header__inner__list__right__box__my__image
        -else
          %ui.header__inner__list__right__box
            .header__inner__list__right__box__do2
              =link_to '新規会員登録',new_user_path,class:"new-member-btm"
            .header__inner__list__right__box__my2
              =link_to 'ログイン',new_user_session_path,class:"new-member-btm2"
= render 'products/breadcrumbs'

app/views/products/all_categories.html.haml
= render 'products/header'


.category-body
  .category-body__full-width
    .category-body__full-width__parts
      いろんなカテゴリ
    .category-body__full-width__item-contents
      .category-body__full-width__item-contents__header
        = @category_name
        の商品一覧
      .category-body__full-width__item-contents__content.clearfix
        - @category_products.each do |category_product|
          .category-body__full-width__item-contents__content__items-box
            = link_to product_path(category_product.id) do
              - if category_product.images[0]
                .category-body__full-width__item-contents__content__items-box--photo
                  = image_tag(category_product.images[0].variant(resize: "188x188"))
                .category-body__full-width__item-contents__content__items-box--body
                  .category-body__full-width__item-contents__content__items-box--body__name
                    = category_product.name
                  .category-body__full-width__item-contents__content__items-box--body__num
                    .category-body__full-width__item-contents__content__items-box--body__num__price
                      =category_product.price
                    .category-body__full-width__item-contents__content__items-box--body__num__like
                      ♡

  .pager
    .pager__num
      1
  .special-description
    .special-description__title
      カテゴリ
    .special-description__text
      カテゴリ説明

= render 'users/footer'

app/views/products/edit.html.haml
= render "products/new_form"

app/views/products/index.html.haml
= render 'products/header'

.top-page-main
  .top-main

    -# スライドヘッダー（特集ページ）
    .top-main-headerbox
      %div
        .top-main__header
          .top-main__header__back
      %div
        .top-main__header2
          .top-main__header__back2
            .top-main__header__back2__box
              .top-main__header__back2__box__left
                %h2.top-main__header__back2__box__left__top
                  スマホでかんたん
                  %br
                  フリマアプリ
                %p.top-main__header__back2__box__left__center
                  メルカリはスマホカメラからすぐに出品できる
                  %br
                  購入時も安心な独自システムのアプリです
                .top-main__header__back2__box__left__bottom
                  .top-main__header__back2__box__left__bottom__icon
                    = link_to('#', {}) do
                      = image_tag "app_store.png", :class =>"image__banner__left__icon__app__apple"
                    = link_to('#', {}) do
                      = image_tag "google_play.png", :class =>"image__banner__left__icon__app__google"
              .top-main__header__back2__box__right
                = image_tag "main_content_pc.png"

    -# カテゴリ一覧
    .top-main__pickup
      %h2.top-main__pickup__head
        ピックアップカテゴリー
      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "レディース 新着アイテム", category_products_path(category_id: 1), method: :get
        .top-main__pickup__select__item
          - @ladys_products.each do |ladys_product|
            .top-main__pickup__select__item__box
              = link_to product_path(ladys_product.id) do
                - if ladys_product.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(ladys_product.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = ladys_product.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = ladys_product.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る", category_products_path(category_id: 1), method: :get

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "メンズ 新着アイテム",category_products_path(category_id: 200), method: :get
        .top-main__pickup__select__item
          - @mens_products.each do |mens_product|
            .top-main__pickup__select__item__box
              = link_to product_path(mens_product.id) do
                - if mens_product.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(mens_product.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = mens_product.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = mens_product.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る",category_products_path(category_id: 200), method: :get

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "ベビー・キッズ 新着アイテム",category_products_path(category_id: 346), method: :get
        .top-main__pickup__select__item
          - @babys_products.each do |babys_product|
            .top-main__pickup__select__item__box
              = link_to product_path(babys_product) do
                - if babys_product.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(babys_product.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = babys_product.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = babys_product.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る",category_products_path(category_id: 346), method: :get

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "コスメ・香水・美容 新着アイテム",category_products_path(category_id: 798), method: :get
        .top-main__pickup__select__item
          - @beauties_products.each do |beauties_product|
            .top-main__pickup__select__item__box
              = link_to product_path(beauties_product.id) do
                - if beauties_product.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(beauties_product.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = beauties_product.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = beauties_product.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る",category_products_path(category_id: 798), method: :get

    -# ブランド一覧        
    .top-main__pickup
      %h2.top-main__pickup__head
        ピックアップブランド

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "シャネル 新着アイテム"
        .top-main__pickup__select__item
          - @chanel.each do |chanel|
            .top-main__pickup__select__item__box
              = link_to product_path(chanel.id) do
                - if chanel.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(chanel.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = chanel.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = chanel.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る"

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "ルイ ヴィトン 新着アイテム"
        .top-main__pickup__select__item
          - @vuitton.each do |vuitton|
            .top-main__pickup__select__item__box
              = link_to product_path(vuitton.id) do
                - if vuitton.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(vuitton.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = vuitton.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = vuitton.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る"

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "シュプリーム 新着アイテム"
        .top-main__pickup__select__item
          - @supreme.each do |supreme|
            .top-main__pickup__select__item__box
              = link_to product_path(supreme.id) do
                - if supreme.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(supreme.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = supreme.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = supreme.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る"

      .top-main__pickup__select
        %h3.top-main__pickup__select__center
          .top-main__pickup__select__center__text
            =link_to "ナイキ 新着アイテム"
        .top-main__pickup__select__item
          - @nike.each do |nike|
            .top-main__pickup__select__item__box
              = link_to product_path(nike.id) do
                - if nike.images[0]
                  .top-main__pickup__select__item__box__phot
                    = image_tag(nike.images[0].variant(resize: "213x213"))
                  .top-main__pickup__select__item__box__details
                    .top-main__pickup__select__item__box__details__name
                      = nike.name
                    .top-main__pickup__select__item__box__details__num
                      .top-main__pickup__select__item__box__details__num__price
                        = nike.price.to_s(:delimited)
                      .top-main__pickup__select__item__box__details__num__like
                        ♡
        .top-main__pickup__select__all
          .top-main__pickup__select__all__text
            =link_to "すべての商品を見る"
  = render 'users/footer'
  = render 'products/bigicon'

app/views/products/new.html.haml
= render "products/new_form"

app/views/products/show.html.haml
%body
  .header
    = render 'products/header'

  .product
    .product__details
      .product__details-name
        = @product.name
      .product__details-main-content.clearfix
        .product__details-photo
          .product__details-photo__all
            - @images.each_with_index do |image,i|
              .product__details-photo__all__selected{"data-big-photo-id": "#{i}"}
                = image_tag(image.variant(resize: "300x300"))

          .product__details-photo__all-img-box
            - @images.each_with_index do |image,i|
              .product__details-photo__all-img-box__dot{"data-small-photo-id": "#{i}"}
                = image_tag(image.variant(resize: "60x60"), id: "small_photo")

        %table.product__details-table
          %tr
            %th 出品者
            %td
              = link_to  "product_path", method: :get  do 
                = @user.nickname
          %tr
            %th カテゴリー
            %td.category_outshow
              = link_to category_products_path(category_id: @category.id ), method: :get do
                = @category.name
              %br
              = link_to '#', method: :get do
                >
                = @category2.name
                %br
              = link_to '#', method: :get do
                >
                = @category3.name
          %tr
            %th ブランド
            %td
              = link_to  "product_path", method: :get  do
                = @product.brand
          %tr
            %th 商品のサイズ
            %td 
              = @product.size.name
          %tr
            %th 商品の状態
            %td 
              = @product.state.name
          %tr
            %th 送料の負担
            %td 
              = @product.burden.name
          %tr
            %th 配送の方法
            %td
              = @product.shipping.name
          %tr
            %th 配送元地域
            %td
              = link_to  "product_path", method: :get  do
                = @product.region.name
          %tr
            %th 発送日の目安
            %td
              = @product.leadtime.name

      .product__details-price-box
        .product__details-price
          = @product.price.to_s(:delimited)
        .product__details-price-tax
          (税込)
        .product__details-price-shipping-fee
          = @product.burden.name
      .product__details-buy-btn
        - unless user_signed_in? && current_user.id == @product.user_id 
          .buy-btn
            = link_to "購入画面に進む", seller_path(@product.id), method: :get, class: "buy-btn-comfirm"

      .product__details-description
        .product__details-description-inner
          = @product.explain
          
      .product__details-btn.clearfix
        .product__details-btn-left
          .product__details-btn-left-like
            いいね
          .product__details-btn-left-report
            報告
        .product__details-btn-right
          安全への取り組み

    .product__messages
      .product__messages-notice
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .product__messages-textarea
        %textarea.message-textarea
        %button.message-btn コメントする
    .product__link-prev-next.clearfix
      .product__link-prev
        - if @product.previous.present?
          = link_to product_path(@product.previous) do
            <
            = @product.previous.name

      .product__link-next
        - if @product.next.present?
          = link_to product_path(@product.next) do
            = @product.next.name
            >

    .product__sns
      .product__sns-box
        %li.product__sns-link
          .FB facebook
        %li.product__sns-link
          .TW twetter
        %li.product__sns-link
          .PT pinterest

    .product__other-items
      .product__other-items--header
        = link_to "product_path", method: :get,  class: "other-items-header" do
          =@user.nickname
          さんのその他の出品
      .product__other-items-content.clearfix
        - @my_products.each do |my_product|
          .product__other-items-box
            = link_to product_path(my_product.id) do
              - if my_product.images[0]
                .product__other-items-box--photo
                  = image_tag(my_product.images[0].variant(resize: "220x220"))
                .product__other-items-box--body
                  .product__other-items-box--body__name
                    = my_product.name
                  .product__other-items-box--body__num
                    .product__other-items-box--body__num__price
                      =my_product.price.to_s(:delimited)
                    .product__other-items-box--body__num__like
                      ♡

      .product__other-items--header
        = link_to "product_path", method: :get, class: "other-items-header" do
          カテゴリのその他の出品
      .product__other-items-content.clearfix
        - @brand.each do |brand|
          .product__other-items-box
            = link_to product_path(brand.id) do
              - if brand.images[0]
                .product__other-items-box--photo
                  = image_tag(brand.images[0].variant(resize: "220x220"))
                .product__other-items-box--body
                  .product__other-items-box--body__name
                    = brand.name
                  .product__other-items-box--body__num
                    .product__other-items-box--body__num__price
                      =brand.price.to_s(:delimited)
                    .product__other-items-box--body__num__like
= render 'users/footer'